### ISSUE TITLE
Color-settings broken after VS-restart

### ISSUE THREAD

**Issue by codingfreak** [mike-ward/VSColorOutput#13]
VS 2015:
If you change the color-settings and restart the studio the default colors will be taken again. You have to open the VSColorOutput options via Tools -> Options -> VSColorOutput again and hit "Ok" without any change (the new color is restored in settings correctly). After the OK-click the output window gets updated correct immediately.

**Comment by mike-ward** [comment]
I'm not entirely sure I'm following this. Here's what I did

- start VS2015
- Open project and build
- Go to VSColorOutput options, change "Build Message" color to purple.
- Click OK to close dialog.
- Restart Visual Studio
- Open project and build

In my test the "Build Message" color is purple as expected. Is this the sequence of steps you're describing?

**Comment by jakubsuchybio** [comment]
I have the same problem. 
Open VS -> Open project -> Build -> Output has default colors -> Openning VSColorOutput settings and they are loaded correctly -> Hit OK to confirm -> Build -> Output colors are correct now -> Restart VS -> Open project -> Build -> Output has default colors.

So VSColorOutput Settings are loading correctly when showed for change. But colors are not loaded correctly from the start of VS.

**Comment by mike-ward** [comment]
Sounds like I may have a race condition at start up.

**Comment by codingfreak** [comment]
@mike-ward Your steps where right. You only missed the restart of the studio. Just wanted to answer your question :-). @jakubsuchybio described my issue completely correct.

**Comment by mike-ward** [comment]
Please check if this is resolved in 2.2.1

**Comment by jakubsuchybio** [comment]
Tried it. The problem persists.

**Comment by codingfreak** [comment]
not fixed with the 2.2.1.

**Comment by codingfreak** [comment]
I have to correct my last posting. The behavior is slightly different now. When I go to Tools -> Options ->VSColorOutput the colors are corrected immediately (without hitting "OK" in the VS-option dialog). So something has changed.

**Comment by jakubsuchybio** [comment]
Yes, that changed. With opening subtree of VSColorOutput it corrects colors. But still doesn't work after start of VS2015.

**Comment by codingfreak** [comment]
@mike-ward Can you tell us if this will be solved in the near future? Thx!

**Comment by jakubsuchybio** [comment]
Hi, I got it somehow magically working and I didn't even do anything to it :D
I only changed settings on my BuildVision plugin to not show up at build startup, so Ouput window is showing at build startup and it have correct colors that I have in settings.

**Comment by codingfreak** [comment]
@jakubsuchybio What do you mean by "BuildVision"?

**Comment by jakubsuchybio** [comment]
It is another extension

**Comment by codingfreak** [comment]
I've recognized that the color settings are restored when I open my VS in light mode. This error only occurs when I set the VS to dark mode and re-start it won't restore the colors from settings.

**Comment by codingfreak** [comment]
@mike-ward Any updates on this? Thx!

**Comment by jakubsuchybio** [comment]
I no longer have any problem

**Comment by mike-ward** [comment]
Without a reproducible scenario here there's not much I can do.

**Comment by mike-ward** [comment]
Without a reproducible scenario here, there's not much I can do. It's relatively easy to debug in VS2015. Perhaps you can find it?

**Comment by codingfreak** [comment]
Ok! I placed a little [GIF ani](https://devdeer.blob.core.windows.net/share/test.gif) to show the steps. Keep in mind, that my problem only occurs in dark theme. First you see my VS after I opened it and hit play once. As you can see, the Info-Style is the default dark blue. I then switch to Tools -> Options -> VSColorOutput. You can see, that I set Information to CornflowerBlue. When I now hit OK (without changing any option really) VS will correct my output window and this will work until the next VS restart.

Funny thing: When I'm in Light or Blue Theme (in other words if the background of the output window is light colored), CornflowerBlue is applied at startup without any problems. 

I guess VSColorOutput initializes incorrect when dark theme is selected.

**Comment by oysteinkrog** [comment]
I also have this bug, both VS 2015 and VS 2016/15.

**Comment by mike-ward** [comment]
You can edit the settings file directly (it's json) and set your colors there.

**Comment by codingfreak** [comment]
@mike-ward Which settings file do you mean? Just to clear that out: The settings are shown and restored correctly when you enter the settings dialog. They are just not assinged to the studio after a restart before you hit ok when it is in dark mode. I dont' understand what changing the settings in the JSON could change.

**Comment by mike-ward** [comment]
I was referring to settings where the colors are stored in the AppData folder. So the issue is the colors are "remembered" but don't affect the output window until you visit the VSColorOutput settings dialog and press OK. This occurs only in the dark theme. Is this correct?

Assuming that it is, I can't repro it. I switched to the dark theme, changed the build messages to Orange. Restart VS. Load same project. Build. Output window has Orange build messages.

I'll run in dark theme for the next couple of days to see if I notice anything..

There was a bug a while back about a crash on C++ projects. That eventually came down to a collision with another extension and it was something the other extension maker had to fix (Kudos to them). It's possible there's a similar problem with here.

Can you list the extensions you're using?

**Comment by oysteinkrog** [comment]
I think ReSharper may be related, I've seen color "race conditions" with it before.

Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA767
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA767
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA767
Microsoft Visual C++ 2015

Visual F# 2015   00322-20000-00000-AA767
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA767
Windows Phone SDK 8.0 - ENU

Advanced Installer Extension   12.5
Advanced Installer Extension. For more information visit the Advanced Installer website at www.advancedinstaller.com. Copyright © Caphyon LTD. All rights reserved.

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

EmojiVS   1.0
GitHub Emojis in Visual Studio

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

HLSL Tools for Visual Studio   0.9.42
Enhanced support for editing HLSL in Visual Studio

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

NuGet Package Manager   3.4.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40315.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40315.00
Profiling support for Python projects.

ShowMyGitBranch   1.0
Displays the name of your current git branch in Visual Studio's title bar.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

TargetFrameworkMigrator   1.0
Bulk Change .Net Projects Target Frameworks

TortoiseGitToolbar   1.0
Lightweight toolbar for launching commonly used TortoiseGit functionality from within Visual Studio.

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Visual Studio Tools for Universal Windows Apps   14.0.25123.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VSColorOutput   2.4
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

VsVim   2.1.0.0
VsVim is a Vim emulator for Visual Studio

**Comment by mike-ward** [comment]
I run Resharper as well.

I was thinking of loading the same extensions to try and reproduce the issue but that list is longer than I expected.

Next time you do a fresh install, Load VSColorOuput first and see if the issue persists.

**Comment by codingfreak** [comment]
@mike-ward Sorry for the delay. Here ist the list of my extensions:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA491
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-80000-00000-AA491
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA491
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA491
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA491
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA491
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   5.206.60517.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Bundler & Minifier   1.9.155
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Crystal Reports for .NET Framework   
Crystal Reports for .NET Framework


GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Infragistics Version Utility   1.0
This utility lets you set the Infragistics version that a specific project is using.

Infragistics.ColorTuner   1.0
Infragistics Color Tuner for Microsoft Visual Studio 2010. For more information visit http://www.infragistics.com

Infragistics.VSExtension   1.0
Infragistics Visual Studio Extension (AddIn) adds scheduled check for update functionality to your Visual Studio IDE. It also provides some fast shortcuts to infragistics products and online resources.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2015.1   Build 102.0.20150408.145317
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft .NET Core Tools (Preview 1)

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

NuGet Package Manager   3.4.3
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23928
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SlowCheetah - XML config transforms    1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.30.0
TypeScript tools for Visual Studio

Typewriter   1.0
Provides automatic TypeScript Template generation from C# source files

Visual Studio Tools for Universal Windows Apps   14.0.25208.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VSColorOutput   2.4
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

WakaTime   1.0


Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.2   2.0.214
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.0.3.214 (0dd817c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Inspector Support   0.7.1.0 (545e74c)
Adds support for inspecting Xamarin and WPF apps.

Xamarin.Android   6.0.3.5 (a94a03b)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.6.1.8 (3a25bf1)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by mike-ward** [comment]
I'm starting to feel extension poor in use of VS :disappointed:

**Comment by oysteinkrog** [comment]
A default install has a lot of extensions...

**Comment by AleksandarDev** [comment]
@mike-ward Maybe it's a problem with Output window being open from start. I see that you described building project to see that colors are ok. Can you try to set your VS window layout to open Output window at startup. 

I'm also using dark theme and ReSharper.

I can debug the extension if required, can you provide me with a link to instructions on how to do it?

**Comment by codingfreak** [comment]
@AleksandarDev, @mike-ward  That makes sense. I think that the initialization gets somehow overwritten when one uses a different theme. Could it be possible that a theme initializes after VSColorOutput and thus simply overwrites the output window? This would explain the behavior.

**Comment by AleksandarDev** [comment]
This is fixed in VS2017 for me, can someone check if this is still a problem in 15?
